### ISSUE TITLE
No Progress Bar on file upload

### ISSUE THREAD

**Issue by marcoRS** [Ink/filepicker-android#48]
There is no longer a progressbar when a file is being uploaded. A toast briefly shows up when first uploading but no indicator after that. The UX can be improved with a progress bar, otherwise a user will not know to wait and might press back or home before a file is uploaded. This would affect the UX of the app using filepicker-android.

**Comment by mtariquekhan** [comment]
Is there any to know percentage progress while uploading a particular file ?

**Comment by shawnmaten** [comment]
Currently there is not, but it’s been my intention to have that from the
beginning. The underlying Java SDK needs some fixing for it though. If you
want, you can follow the linked issue. Progress on that issue will precede
adding the functionality here.

filestack/filestack-java/issues/51
<https://github.com/filestack/filestack-java/issues/51>

**Comment by shawnmaten** [comment]
Okay I didn’t realIze this issue was so old. If you’re referring to the latest versions (5.0.0-0.1.0+) then I expect us to add this in the not-too-distant future. If you’re referring to a much older major version, you won’t get any new functionality unless you update to the latest major version.

Please note, there were a few versions misnamed (2.0.0-alpha.x) that really fall under major version.

So if you’re using a recent release, you should expect to get this functionality without much change. Although honestly it’s not too much work to change from older versions.

**Comment by mtariquekhan** [comment]
Actually I am referring https://github.com/filestack/filestack-android to integrate filestack in my android project. But didn't come to now how can I get the percentage while uploading the individual file.

**Comment by shawnmaten** [comment]
This codebase (filestack-android) is based on another codebase (filestack-java). The feature you're asking for, progress percentages, is related to work that needs to be done in the latter. That's why I'm referencing it.

**Comment by shawnmaten** [comment]
Since this issue is very old and relates to code that's now gone, I've opened up #155 to track this. You can follow that issue for updates. Please make further comments there so we can keep everything together.

**Comment by mtariquekhan** [comment]
Sure
