### ISSUE TITLE
Memory Leak 3.7.3

### ISSUE THREAD

**Issue by marcoRS** [Ink/filepicker-android#61]
FilePicker has a memory leak. It can be observed when rotating a device a couple of times. Using Strict Mode, you will receive a "InstanceCountViolation" and from the Memory Analyzer screenshot you can see that there is multiple FilePicker Activity entries. 

![screen shot 2015-01-09 at 11 49 04 am](https://cloud.githubusercontent.com/assets/507510/5686215/ff361de8-97f5-11e4-8d50-27231c83c627.png)

**Comment by maciejwitowski** [comment]
Hi,

Indeed, this was due to a poor design decision of adding/removing multiple activities in the activities stack when user traverses the folders tree.

I've worked on this and change it to having single activity which content is being refreshed as user traverses the folder tree. In order not to make unnecessary network calls, when user goes into a folder, the folder's content is being stored in temporary json file. So when user goes back, the cached data is used instance of making calls to api.

I think it's a performance-wise solution, please let me know if you have any suggestions.
