### ISSUE TITLE
Clearing Filepicker cache on logout

### ISSUE THREAD

**Issue by marcoRS** [Ink/filepicker-android#65]
How do we go about clearing the Filepicker cache? 

The use case would be that if someone logs out of our app and logs in under another account, they should not be logged in to any Cloud accounts in Filepicker.

**Comment by maciejwitowski** [comment]
In 3.8.1 you can use public Filepicker.clearSession(Context context) method. For now though it clears all cookies so I think it may affect you application (but since you want to use it on user's logout, it should works fine for you, right?).

I will look also for a way to clear only Filepicker's session cookie.

**Comment by marcoRS** [comment]
That should work for my current needs. Thanks!

**Comment by marcoRS** [comment]
Hello, 
        When using the clear session method. I get a method not found exception. 

https://github.com/Ink/filepicker-android/blob/master/filepicker-library/src/io/filepicker/utils/SessionUtils.java#L41

In this method both methods were introduced at API 21

**Comment by maciejwitowski** [comment]
You're right. Seems to be finally fixed in version 3.8.2
