### ISSUE TITLE
Feature Request extra Meta Data

### ISSUE THREAD

**Issue by marcoRS** [Ink/filepicker-android#66]
Would be great if Filepicker returned image resolution, orientation and dimens  in FPFile

**Comment by maciejwitowski** [comment]
I don't think this is a good idea for library, since FPFile may contain many types of files and what's more, the library's users' needs vary (for most of them these params aren't important).

Fortunately having FPFile url you have 2 options:
1) Make a call to Filepicker API for metadata:
Eg, to get file's size, width and height: https://www.filepicker.io/api/file/VoszPWsOT52E1sU8s5yy/metadata size=true&height=true&width=true

The full list of possible stats is here: https://developers.filepicker.io/docs/web/javascript_api/#stat

2) If you're looking for stat which isn't returned by API you can retrieve the file and locally get all kind of data about it.
